name: Create draft release on project closed

on:
  project:
    types: closed
    
jobs:
  publish-release:
    runs-on: ubuntu-latest
    steps:
      - name: Extracting release name from project
        id: release_name_extracting
        run: |
          RELEASE_NAME=$(echo "${{ github.event.project.name }}")
          echo "::set-output name=release_name::${RELEASE_NAME}"
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v2
          release_name: New release
          body: |
              Changes in this Release
              - First Change
              - Second Change
          draft: true
          prerelease: false
