name: New release from project

on:
  project:
    types: closed

# gets the project’s name and uses it as the new release name

jobs:
  create-new-release:
    runs-on: ubuntu-latest
    steps: 
      - name: Get project name
        id: get_project_name
        run: |
          PROJECT_NAME=$(echo "${{ github.event.project.name }}" | grep -Po 'nsh \Kv[0-9]+\.[0-9]+\.[0-9]+')
          echo "::set-output name=project_name::${PROJECT_NAME}"
    
      - name: Create new release
        id: create_new_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.get_project_name.outputs.release_name }}
          release_name: Release ${{ steps.release_name_extracting.outputs.project_name }}
          body: |
            A new release :tada:
          draft: true
          prerelease: false
