name: reviewdog

on: 
  pull_request:
    types: [opened, edited, reopened]

jobs:
  misspell:
    name: check for misspelling
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v1
      - name: looks for misspellings
        uses: reviewdog/action-misspell@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          locale: "US"
          reporter: github-pr-check
          level: info
